### ISSUE TITLE
Crashing on VG build

### ISSUE THREAD

**Issue by ghost** [monster860/FastDMM#1]
![ukdcigr](https://cloud.githubusercontent.com/assets/285438/17467953/bfa6d2b2-5ce8-11e6-84e1-2f0c8b8a5e89.png)
![c6tlytu](https://cloud.githubusercontent.com/assets/285438/17467954/c0adefb0-5ce8-11e6-9dba-7f33faf743e1.png)
![jsaivm4](https://cloud.githubusercontent.com/assets/285438/17467955/c1b4dbb2-5ce8-11e6-8670-454789779cf0.gif)

**Comment by monster860** [comment]
Try different object filters and see what is the type of the object that's causing this crash.

**Comment by ghost** [comment]
It works with /obj off.

**Comment by monster860** [comment]
Try having just one of each: `/obj/structure`, `/obj/machinery`, `/obj/effect`, `/obj/item`

And then tell me which one it crashes on.

**Comment by ghost** [comment]
Both /obj/machinery and /obj/item

**Comment by Jordie0608** [comment]
If it helps, this doesn't occur with TG master.

**Comment by ZeWaka** [comment]
This occurs with the Goonstation release as well.
Different error though, not all of them have null in it.
![sublime_text_2016-08-07_20-36-37](https://cloud.githubusercontent.com/assets/4741640/17471279/bc1d7308-5cde-11e6-879e-740a44c2f4a3.png)

Maybe it's an error where it can't handle decimal layers? As in, not flat numbers?

**Comment by monster860** [comment]
@wakafanykai123 Does it actually _crash_ on goonstation though?
