### ISSUE TITLE
Icon Generation Funkiness

### ISSUE THREAD

**Issue by ZeWaka** [monster860/FastDMM#10]
If you select false_wall turfs on Goonstation, it displays the entire DMI it points to as it's icon, rather than just the icon_state.

I've also crashed by right clicking on them.
![2016-08-09_15-27-23](https://cloud.githubusercontent.com/assets/4741640/17538964/cc6a2dba-5e45-11e6-923b-a5cacb804e91.png)

![2016-08-09_15-29-08](https://cloud.githubusercontent.com/assets/4741640/17538993/0e427580-5e46-11e6-98fa-442bba2ccb93.png)

Also, it generates a half-transparent set of the door DMI with it being invisible on the object sidebar. This is what happens when you place it around.
![2016-08-09_15-34-52](https://cloud.githubusercontent.com/assets/4741640/17539079/e200f95a-5e46-11e6-9d39-da9715e1f822.png)

Another variant, this time a /obj/fakeobject on Z3.

![2016-08-09_15-53-38](https://cloud.githubusercontent.com/assets/4741640/17539377/83439f3c-5e49-11e6-8893-4492b20dd88e.png)

**Comment by ghost** [comment]
The WTF label sure fits on this one, I'm not even sure how this would occur but I'd assume it's one of the many regexes fucking up somewhere.

**Comment by monster860** [comment]
I've figured out why this happens.

Apparently, old formats of DMI used to store everything in one row, and the dimensions of said row is determined by the amount of states defined.

http://www.byond.com/forum/?post=133191
