### ISSUE TITLE
NullPointerException on Baystation RandomZLevels

### ISSUE THREAD

**Issue by ZeWaka** [monster860/FastDMM#12]
How to reproduce:
1. Get baystation DME loaded up.
2. Open a /randomzlevesl/ map. I used beach and blackmarketpackers.
3. Try to pan to the middle, but get a mean error!

![2016-08-09_15-57-28](https://cloud.githubusercontent.com/assets/4741640/17539456/29c7a8c6-5e4a-11e6-8e25-073e2fce98ab.png)

Edit 1: Similar, but different error. This occured on the torch-1 map.

![2016-08-09_16-04-56](https://cloud.githubusercontent.com/assets/4741640/17539595/0c53f26c-5e4b-11e6-849e-7cc63f3555d3.png)

Edit 2: This also occurs on some Goonstation maps.

**Comment by ghost** [comment]
Our exception handling could use some love indeed.

**Comment by d34d10cc** [comment]
I'm 99% sure this was the same issue as #23

**Comment by monster860** [comment]
Nope, completely different.

**Comment by d34d10cc** [comment]
I meant the last picture, sorry.
