### ISSUE TITLE
Does not support FILE_DIR

### ISSUE THREAD

**Issue by rouge** [monster860/FastDMM#17]
Relative pathing still exists on older codebases

**Comment by ghost** [comment]
Relative pathing is also widely used in some not-so-old codebases [😉]

**Comment by monster860** [comment]
I thought relative pathing was supported.

Give me a good example of code that doesn't work.

**Comment by rouge** [comment]
r4407 does not work, I can confirm its relative pathing because I changed the icon var to a literal path and the icon loaded.

**Comment by monster860** [comment]
Please paste the offending code here with ``` around it.

**Comment by rouge** [comment]
`entire rev4407 goonstation release`

**Comment by monster860** [comment]
Create a simple dme test case where relative path doesn't work and send it

**Comment by rouge** [comment]
https://github.com/duncathan/goon-r4407-510

**Comment by PJB3005** [comment]
Which words in the phrase "simple test case" don't you understand?

**Comment by rouge** [comment]
Why are you making a big deal out of this @PJB3005?

This is the exact code where I am trying to use FastDMM, this is 100% better than a "simple test case"

**Comment by PJB3005** [comment]
It's way harder to find a bug in a big project than in a simple test case.

**Comment by monster860** [comment]
@rouge This has literally nothing to do with relative pathing.

The issue is FILE_DIR.

**Comment by rouge** [comment]
@monster860 this is what I figured, removing specific paths from the DME fixes it.

IE: "FILE_DIR "icons/turf""

**Comment by optimumtact** [comment]
> they still define FILE_DIR

**Comment by ghost** [comment]
Adding support for `FILE_DIR` is not worth it IMO.

**Comment by PJB3005** [comment]
No it definitely is, a lot of byond projects use it and it's not that hard to implement.

**Comment by optimumtact** [comment]
If you use FILE_DIR you deserve death

**Comment by PJB3005** [comment]
Look, we can either go down the "how it should be route", or allow FILE_DIR and get more people interested.
