### ISSUE TITLE
No 'previously opened files'

### ISSUE THREAD

**Issue by ZeWaka** [monster860/FastDMM#22]
Would be a great improvement, seeing as my .dme files are located deep within my system and it's a massive pain to navigate to them every time.

**Comment by PJB3005** [comment]
I wonder where we should store this data? `~/.fastdmm` on Unix and `%appdata%/fastdmm` on windows?

**Comment by bauen1** [comment]
On mac that would be `~/Library/Application\ Support/fastdmm/` if you don't want to clutter the home dir too much
