### ISSUE TITLE
Map screenshots

### ISSUE THREAD

**Issue by optimumtact** [monster860/FastDMM#33]
We have the occasional requirement to produce high quality screenshots of our maps, which generally involves handstitching shots of dreammaker together to form a final map.

Is there potential to take FastDMM's render output and write it to a png file and where in the code should I look to investigate this?

**Comment by d34d10cc** [comment]
There is certainly potential. Where you would have to look would be beyond
me.

**Comment by monster860** [comment]
You could probably generate a giant OpenGL framebuffer and have it render the map to that. It would require no hand-stitching.

**Comment by monster860** [comment]
Also, have you tried setting the "view" variable on the client in a local server to "31", and using byond's native screenshot functionality to take large screenshots? (Be warned, top and bottom rows will not have borders on the edges of a tile)

**Comment by optimumtact** [comment]
Yeah I found where the rendering is happening for the viewpoint, so I'll try with a giant framebuffer

we've used all the different methods in byond, what I want is an automated solution that I can drive from a commandline, so I thought I'd just wrap a layer around FastDMM's rendering

**Comment by ZeWaka** [comment]
This could probably be closed now, since this has been added.
