### ISSUE TITLE
Copy + Paste selection is acting like Cut + Paste

### ISSUE THREAD

**Issue by ZeWaka** [monster860/FastDMM#37]
How to reproduce:

1. Select turf with objs on it.
2. Go to select mode and select the tile.
3. Right click and click copy selection.
4. Mouse over to a new tile, right click, and press paste.
5. Your original selected objs and turf are gone, like they were 'cut'.

Used Version: 0.6 prerelease

**Comment by monster860** [comment]
I cannot seem to reproduce this issue on 0.6. Here's what I did:

1. I selected a turf with objs on it in select mode
2. Right clicked, it, copy
3. Pasted somewhere else
4. Nothing happened to the original

**Comment by ZeWaka** [comment]
[Video](https://streamable.com/90qso)

Cut seems to perform as intended and deletes the target tile as soon as you press cut. However, copy deletes the source once you 'paste' it down.

**Comment by monster860** [comment]
I see what's going on, you clicked the selection twice. You only want to click the selection once. Anyways, I'll see about fixing this issue properly, but to have this work properly, do not left click the selection after you have made it
