### ISSUE TITLE
Questions regarding packaging.

### ISSUE THREAD

**Issue by ghost** [monster860/FastDMM#4]
I've been spending the past day or so building a set of [gradle](https://gradle.org/) and [capsule](http://www.capsule.io/) build files and configurations to make it require less effort for people to distribute and contribute to fastDMM

I however have a few remaining questions before i submit this PR.
- Should we distribute a windows executable that has been generated trough launch4j which contains all requirements to run FastDMM.
- Do we want to distribute a platform independent jar file that has been generates trough capsule which contains all requirements and it's own JRE to run FastDMM.
- Do we want to automate this process using [travis](https://travis-ci.org/) allowing pull requests to be tested before they are merged?

**Comment by PJB3005** [comment]
> Do we want to automate this process using travis allowing pull requests to be tested before they are merged?

I think that's definitely a yes no matter what.

**Comment by d34d10cc** [comment]
I am completely positive on the Travis one. I'm leaning towards
multiplatform, although most (all?) BYOND users use Windows. So, my vote
goes to the independent JAR file.

**Comment by ghost** [comment]
@CrAzYPiLoT-SS13 we can easily do both.

**Comment by d34d10cc** [comment]
That would be ideal, in that case.

**Comment by ghost** [comment]
#5 has been opened, i decided to ditch the .exe generation as it was causing some issues, this should make building and running this a lot easier :+1:
