### ISSUE TITLE
If FastDMM is not an abandoned then requesting Unicode support!

### ISSUE THREAD

**Issue by Gesugao-san** [monster860/FastDMM#51]
Read more about this please: http://www.byond.com/forum/post/2520672

There is no DDM-analog editors with support non-English characters in WHOLE INTENET!

Maybe… Someday… I will see this characters as are normal symbols, not something weird… p.. please..

**Comment by 4310V343k** [comment]
There is. StrongDMM by Spair

**Comment by SanecMan** [comment]
> Read more about this please: http://www.byond.com/forum/post/2520672
> 
> There is no DDM-analog editors with support non-English characters in WHOLE INTENET!
> 
> Maybe… Someday… I will see this characters as are normal symbols, not something weird… p.. please..

![image](https://user-images.githubusercontent.com/36476150/124377064-42fd3500-dcd4-11eb-8457-acc26d0797f4.png)

**Comment by 4310V343k** [comment]
Outdated, i guess
BYOND is unicode-friendly now
